
#query numbers:
QUERY_DB_ACTIVE = 0
QUERY_GET_ACTIVE_DRONES = 1
QUERY_GET_FLIGHT_RECORDS = 2
QUERY_GET_FLIGHT_TIME_FOR_DRONE = 3
QUERY_GET_CURRENT_FLIGHT_DETAILS = 4
QUERY_GET_SETUP_SUGGESTIONS = 5
QUERY_GET_ALL_FLIGHTS = 6
QUERY_GET_DRONE_SUM_REPORT = 7
QUERY_GET_TABLE = 8
QUERY_UPDATE_TABLE = 9
QUERY_ADD_SINGLE_TO_TABLE = 10
QUERY_ADD_MULTI_TO_TABLE = 11
QUERY_DELETE_FROM_TABLE = 12

#current page
CURRENT_PAGE_INDEX = 0
CURRENT_PAGE_FLIGHT_MONITOR = 1
CURRENT_PAGE_DRONE_SETUP_MAIN = 2
CURRENT_PAGE_DRONE_SETUP_PROGRESS = 3
CURRENT_PAGE_DRONE_SETUP_RESULT = 4
